version: '3.8'
services:
  api:
    container_name: tesafastapi2
    build: ./backend 
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/application:ro
    depends_on:
      - db
    

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


